## 张量
Tensor(张量)类似于Numpy的ndarray,但是还可以在GPU上使用加速计算

In [1]:
from __future__ import print_function
import torch

In [3]:
#床架一个没有初始化的5*3的矩阵
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.1704e-41],
        [0.0000e+00, 2.2369e+08, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [       nan,        nan, 8.7449e-37]])


In [4]:
#创建一个随机初始化矩阵
x = torch.rand(5, 3)
print(x)

tensor([[0.0147, 0.7039, 0.0326],
        [0.9560, 0.6162, 0.3584],
        [0.2005, 0.3889, 0.7750],
        [0.7529, 0.2878, 0.0333],
        [0.4974, 0.6801, 0.8139]])


In [6]:
#创建一个填满0且类型是long的矩阵
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
#直接从数据构建张量
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
#根据已有的tensor建立新的tensor,除非提供新的值,斗则这些方法将重用输入张量的属性
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

x = torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.1492, 0.4448, 0.2332],
        [0.5647, 0.3428, 0.3211],
        [0.2747, 0.3288, 0.3825],
        [0.1067, 0.4612, 0.6010],
        [0.3897, 0.2342, 0.0221]])


In [9]:
#获取张量的形状
print(x.size())

torch.Size([5, 3])


> torch.Size本质上还是tuple,支持tuple的一起操作

## 运算

In [21]:
# 加法
y = torch.rand(5, 3)
print(x)
print(y)
print("第一种形式:x+y")
print(x + y)
print("第二种形式:torch.add(x, y)")
print(torch.add(x, y))
print("第三种形式:给定一个输出张量作为参数 out=result")
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
print("第四种形式:原位/原地操作(in-place)")
print(y.add_(x))

tensor([[0.1492, 0.4448, 0.2332],
        [0.5647, 0.3428, 0.3211],
        [0.2747, 0.3288, 0.3825],
        [0.1067, 0.4612, 0.6010],
        [0.3897, 0.2342, 0.0221]]) tensor([[0.6788, 0.9013, 0.9111],
        [0.0757, 0.6049, 0.2100],
        [0.6781, 0.2057, 0.5511],
        [0.4034, 0.8253, 0.5214],
        [0.9979, 0.8502, 0.5180]])
tensor([[0.6788, 0.9013, 0.9111],
        [0.0757, 0.6049, 0.2100],
        [0.6781, 0.2057, 0.5511],
        [0.4034, 0.8253, 0.5214],
        [0.9979, 0.8502, 0.5180]])
第一种形式:x+y
tensor([[0.8279, 1.3462, 1.1444],
        [0.6404, 0.9477, 0.5311],
        [0.9528, 0.5345, 0.9336],
        [0.5101, 1.2865, 1.1223],
        [1.3876, 1.0844, 0.5402]])
第二种形式:torch.add(x, y)
tensor([[0.8279, 1.3462, 1.1444],
        [0.6404, 0.9477, 0.5311],
        [0.9528, 0.5345, 0.9336],
        [0.5101, 1.2865, 1.1223],
        [1.3876, 1.0844, 0.5402]])
第三种形式:给定一个输出张量作为参数 out=result
tensor([[0.8279, 1.3462, 1.1444],
        [0.6404, 0.9477, 0.5311],
        [0.9528

> 注意:
任何一个in-place改变张量的操作后面都固定一个_。例如x.copy_(y)、x.t_()将更改x

In [23]:
# 可以使用像Numpy使用索引进行操作
print(x)
print(x[:, 1])

tensor([[0.1492, 0.4448, 0.2332],
        [0.5647, 0.3428, 0.3211],
        [0.2747, 0.3288, 0.3825],
        [0.1067, 0.4612, 0.6010],
        [0.3897, 0.2342, 0.0221]])
tensor([0.4448, 0.3428, 0.3288, 0.4612, 0.2342])


In [26]:
# 改变形状:使用torch.view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1是从其他尺寸推断的
print(x)
print(y)
print(z)
print(x.size(), y.size(), z.size())

tensor([[-0.8648, -0.3935, -0.1712, -0.5305],
        [-1.5016,  0.5812,  0.5898, -1.1872],
        [-0.4456, -1.2171, -0.5073,  0.1688],
        [ 1.7078, -0.8416, -0.7522,  0.9512]])
tensor([-0.8648, -0.3935, -0.1712, -0.5305, -1.5016,  0.5812,  0.5898, -1.1872,
        -0.4456, -1.2171, -0.5073,  0.1688,  1.7078, -0.8416, -0.7522,  0.9512])
tensor([[-0.8648, -0.3935, -0.1712, -0.5305, -1.5016,  0.5812,  0.5898, -1.1872],
        [-0.4456, -1.2171, -0.5073,  0.1688,  1.7078, -0.8416, -0.7522,  0.9512]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [27]:
# 如果是仅包含一个元素的tensor，可以使用.item()来得到对应的python数值
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6300])
-0.6300126314163208


## 桥接NumPy
Torch张量和NumPy数组将共享它们底层内存位置,因此一个改变时另一个也同时改变

In [28]:
# 将torch的Tensor转为NumPy的数组
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [30]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [31]:
# 测试NumPy数组改变数值
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [33]:
# 将NumPy数组装维tensor张量
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)
np.add(a, 1, out = a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


> CPU上的所有张量(CharTensor除外)都支持与Numpy的相互转换。

## CUDA上的张量
张量可以使用.to方法移动到任何设备上

In [34]:
# 当GPU可用时
# 将使用torch.device来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

# Autograd:自动求导

PyTorch中，所有神经网络的核心是 `autograd` 包
`autograd` 包为张量上的所有操作提供了自动求导机制。它是一个在运行时定义(define-by-run）的框架，这意味着反向传播是根据代码如何运行来决定的，并且每次迭代可以是不同的.
## 张量

`torch.Tensor` 是这个包的核心类。如果设置它的属性 `.requires_grad` 为 `True`，那么它将会追踪对于该张量的所有操作。当完成计算后可以通过调用 `.backward()`，来自动计算所有的梯度。这个张量的所有梯度将会自动累加到`.grad`属性.

要阻止一个张量被跟踪历史，可以调用 `.detach()` 方法将其与计算历史分离，并阻止它未来的计算记录被跟踪。

为了防止跟踪历史记录(和使用内存），可以将代码块包装在 `with torch.no_grad()`: 中。在评估模型时特别有用，因为模型可能具有 `requires_grad = True` 的可训练的参数，但是我们不需要在此过程中对他们进行梯度计算。

还有一个类对于autograd的实现非常重要：`Function`。

`Tensor` 和 `Function` 互相连接生成了一个无圈图(acyclic graph)，它编码了完整的计算历史。每个张量都有一个 `.grad_fn` 属性，该属性引用了创建 `Tensor` 自身的`Function`(除非这个张量是用户手动创建的，即这个张量的 `grad_fn` 是 `None` )。

如果需要计算导数，可以在 `Tensor` 上调用 `.backward()`。如果 `Tensor` 是一个标量(即它包含一个元素的数据），则不需要为 `backward()` 指定任何参数，但是如果它有更多的元素，则需要指定一个 `gradient` 参数，该参数是形状匹配的张量。

In [35]:
import torch

In [36]:
#创建一个张量并设置requires_grad=True用来追踪其计算历史
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [37]:
#对这个张量做一次运算
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [38]:
print(y.grad_fn)

In [39]:
#对y进行其他操作
z = y * y* 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


`.requires_grad_(...)` 原地改变了现有张量的 `requires_grad` 标志。如果没有指定的话，默认输入的这个标志是 `False`

In [40]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## 梯度
现在开始进行反向传播，因为 `out` 是一个标量，因此 `out.backward()` 和 `out.backward(torch.tensor(1.))` 等价

In [41]:
out.backward()

In [42]:
# 输出导数 d(out)/dx
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
